### ISSUE TITLE
dstripe compile error on rhel6: LLAPI_LAYOUT

### ISSUE THREAD

**Issue by toupeiro** [hpc/mpifileutils#105]
On buildme step @ dstripe (sadly the command I really need rightnow..)    Using lustre_client 2.5.1 devel and openmpi-devel.  also tried with intel mpi, have same issue.  

make[3]: Entering directory `/local/lfs1/mjfg/mpifileutils-master/mpifileutils-0.7/src/dstripe'
mpicc -DHAVE_CONFIG_H -I. -I../..  -I../common/ -I/usr/include/openmpi-1.10-x86_64 -I/local/lfs1/mjfg/mpifileutils-master/install/include/    -std=gnu99 -ggdb -W -pedantic -Wall -Wextra -Wconversion -Wformat=2 -Winit-self -Wmissing-include-dirs -Wswitch-default -Wswitch-enum -Wuninitialized -Wunknown-pragmas -Wstrict-aliasing -Wfloat-equal -Wundef -Wbad-function-cast -Wcast-qual -Wcast-align -Wstrict-prototypes -Wmissing-prototypes -Wredundant-decls -Winline -Wdisabled-optimization -Wshadow -Wwrite-strings -g -O0 -I/local/lfs1/mjfg/mpifileutils-master/src/common -DDCOPY_USE_XATTRS -I/local/lfs1/mjfg/mpifileutils-master/install/include -I/usr/include/openmpi-1.10-x86_64 -MT dstripe-dstripe.o -MD -MP -MF .deps/dstripe-dstripe.Tpo -c -o dstripe-dstripe.o `test -f 'dstripe.c' || echo './'`dstripe.c
dstripe.c: In function ‘generate_suffix’:
dstripe.c:72:23: warning: cast from function call of type ‘int’ to non-matching type ‘double’ [-Wbad-function-cast]
         int set_idx = (double)rand() / RAND_MAX * (sizeof(set) - 1);
                       ^
dstripe.c:72:23: warning: conversion to ‘int’ from ‘double’ may alter its value [-Wfloat-conversion]
dstripe.c: In function ‘get_file_stripe_info’:
dstripe.c:85:35: warning: implicit declaration of function ‘llapi_layout_get_by_path’ [-Wimplicit-function-declaration]
     struct llapi_layout *layout = llapi_layout_get_by_path(path, 0);
                                   ^
dstripe.c:85:35: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
dstripe.c:93:5: warning: implicit declaration of function ‘llapi_layout_stripe_size_get’ [-Wimplicit-function-declaration]
     llapi_layout_stripe_size_get(layout, stripe_size);
     ^
dstripe.c:94:5: warning: implicit declaration of function ‘llapi_layout_stripe_count_get’ [-Wimplicit-function-declaration]
     llapi_layout_stripe_count_get(layout, stripe_count);
     ^
dstripe.c:97:5: warning: implicit declaration of function ‘llapi_layout_free’ [-Wimplicit-function-declaration]
     llapi_layout_free(layout);
     ^
dstripe.c: In function ‘create_striped_file’:
dstripe.c:108:35: warning: implicit declaration of function ‘llapi_layout_alloc’ [-Wimplicit-function-declaration]
     struct llapi_layout *layout = llapi_layout_alloc();
                                   ^
dstripe.c:108:35: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
dstripe.c:113:9: warning: implicit declaration of function ‘llapi_layout_stripe_count_set’ [-Wimplicit-function-declaration]
         llapi_layout_stripe_count_set(layout, LLAPI_LAYOUT_WIDE);
         ^
dstripe.c:113:47: error: ‘LLAPI_LAYOUT_WIDE’ undeclared (first use in this function)
         llapi_layout_stripe_count_set(layout, LLAPI_LAYOUT_WIDE);
                                               ^
dstripe.c:113:47: note: each undeclared identifier is reported only once for each function it appears in
dstripe.c:116:47: error: ‘LLAPI_LAYOUT_DEFAULT’ undeclared (first use in this function)
         llapi_layout_stripe_count_set(layout, LLAPI_LAYOUT_DEFAULT);
                                               ^
dstripe.c:123:5: warning: implicit declaration of function ‘llapi_layout_stripe_size_set’ [-Wimplicit-function-declaration]
     llapi_layout_stripe_size_set(layout, stripe_size);
     ^
dstripe.c:126:10: warning: implicit declaration of function ‘llapi_layout_file_create’ [-Wimplicit-function-declaration]
     fd = llapi_layout_file_create(path, 0, 0644, layout);
          ^
dstripe.c: In function ‘generate_pretty_size’:
dstripe.c:144:18: warning: unused variable ‘unit_len’ [-Wunused-variable]
     unsigned int unit_len;
                  ^
dstripe.c:143:11: warning: unused variable ‘unit’ [-Wunused-variable]
     char *unit;
           ^
dstripe.c: In function ‘filter_list’:
dstripe.c:232:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (curr_stripe_count != stripe_count || curr_stripe_size != stripe_size) {
                                   ^
dstripe.c: In function ‘write_file_chunk’:
dstripe.c:247:21: warning: conversion to ‘uint64_t {aka long unsigned int}’ from ‘long int’ may change the sign of the result [-Wsign-conversion]
     uint64_t base = (off_t)p->offset;
                     ^
dstripe.c:248:26: warning: conversion to ‘uint64_t {aka long unsigned int}’ from ‘long int’ may change the sign of the result [-Wsign-conversion]
     uint64_t file_size = (off_t)p->file_size;
                          ^
dstripe.c:250:28: warning: conversion to ‘uint64_t {aka long unsigned int}’ from ‘long int’ may change the sign of the result [-Wsign-conversion]
     uint64_t stripe_size = (off_t)p->length;
                            ^
dstripe.c:338:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (nread != read_size) {
                   ^
dstripe.c:363:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (nwrite != read_size) {
                    ^
dstripe.c: In function ‘main’:
dstripe.c:434:41: warning: passing argument 2 of ‘mfu_abtoull’ from incompatible pointer type [-Wincompatible-pointer-types]
                 if (mfu_abtoull(optarg, &stripe_size) != MFU_SUCCESS) {
                                         ^
In file included from ../common/mfu.h:44:0,
                 from dstripe.c:42:
../common/mfu_util.h:175:5: note: expected ‘long long unsigned int *’ but argument is of type ‘uint64_t * {aka long unsigned int *}’
 int mfu_abtoull(const char* str, unsigned long long* val);
     ^
dstripe.c:444:41: warning: passing argument 2 of ‘mfu_abtoull’ from incompatible pointer type [-Wincompatible-pointer-types]
                 if (mfu_abtoull(optarg, &min_size) != MFU_SUCCESS) {
                                         ^
In file included from ../common/mfu.h:44:0,
                 from dstripe.c:42:
../common/mfu_util.h:175:5: note: expected ‘long long unsigned int *’ but argument is of type ‘uint64_t * {aka long unsigned int *}’
 int mfu_abtoull(const char* str, unsigned long long* val);
     ^
dstripe.c:478:20: warning: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Wsign-conversion]
         numpaths = argc - optind;
                    ^
dstripe.c:485:52: warning: to be safe all intermediate pointers in cast from ‘char **’ to ‘const char **’ must be ‘const’ qualified [-Wcast-qual]
         mfu_param_path_set_all((uint64_t)numpaths, (const char**)p, paths);
                                                    ^
dstripe.c:486:16: warning: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Wsign-conversion]
         optind += numpaths;
                ^
dstripe.c:486:19: warning: conversion to ‘int’ from ‘unsigned int’ may change the sign of the result [-Wsign-conversion]
         optind += numpaths;
                   ^
dstripe.c:565:11: warning: conversion to ‘unsigned int’ from ‘time_t {aka long int}’ may alter its value [-Wconversion]
     srand(time(NULL));
           ^
dstripe.c:401:9: warning: variable ‘verbose’ set but not used [-Wunused-but-set-variable]
     int verbose = 0;
         ^
make[3]: *** [dstripe-dstripe.o] Error 1
make[3]: Leaving directory `/local/lfs1/mjfg/mpifileutils-master/mpifileutils-0.7/src/dstripe'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/local/lfs1/mjfg/mpifileutils-master/mpifileutils-0.7/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/local/lfs1/mjfg/mpifileutils-master/mpifileutils-0.7'
make: *** [all] Error 2
+ '[' 2 -ne 0 ']'
+ echo 'failed to configure, build, or install mpiFileUtils'
failed to configure, build, or install mpiFileUtils
+ exit 1

**Comment by dinatale2** [comment]
@toupeiro Thank you for opening this issue! I did a little bit of digging and found that the `llapi` functions that `dstripe` is using were only introduced in Lustre 2.6.52 and above. I can try and see if there is a way to make `dstripe` compatible with Lustre versions prior to 2.6.52.

**Comment by dinatale2** [comment]
@toupeiro I've developed a preliminary version of lustre 2.5 support in `dstripe`. It's currently untested since I don't have easy access to a test system with an earlier version of 2.5. Are you able to attempt to build and run dstripe on a test dataset from [here](https://github.com/dinatale2/mpifileutils/tree/lustre-2.5)? I'll try and stand up something so I can build and test it, but that might take a little bit of time.

**Comment by dinatale2** [comment]
@toupeiro This should be taken care of now that #107 has been merged. Let me know if it doesn't resolve it.
