### ISSUE TITLE
dwalk : leverage output file

### ISSUE THREAD

**Issue by jbd** [hpc/mpifileutils#110]
Hello,

what would be the best way to leverage the output of dwalk (-o, --output option) for further treatment ?

I could use the -p, --print option of perform some parsing, but it looks fragile and it does not list every files (<snip>) unless I misunderstood something.

Thank you,

Jean-Baptiste

**Comment by dsikich** [comment]
Hi, so I would recommend writing the output of dwalk to a file. The print option is just setup to print the first 100 or so files to the terminal. Also, if you write the output of dwalk to a file you can speed up large copies of that file tree by reading the file into dcp (avoids the walk). Many of the tools allow you to avoid the walk by reading in the file list from dwalk. You can check for it with the —help option.

**Comment by jbd** [comment]
Thank you for your answer. The output file format is completely internal to the d* tools, correct ? It does not look too complicated, but I'll have to look at the source code if I want to parse it.

**Comment by dsikich** [comment]
@jbd You shouldn't need to parse it. dwalk has an option to write the file list to an output file (--output), and the other tools expect a file list in that format as input.

**Comment by jbd** [comment]
I'd like to use the walk output in a third party tool.

**Comment by dsikich** [comment]
@jbd Oh okay, that makes sense. You could also look at how we parse the input list in the other tools if that will help any.

**Comment by jbd** [comment]
I'll do that, thank you for the input =)
