### ISSUE TITLE
Compiling on Cray Supercomputer

### ISSUE THREAD

**Issue by jtchilders** [hpc/mpifileutils#131]
Hello,
I've tried compiling on a Cray supercomputer on which I'd like to use your mpi file utils. However, when I run buildme_depenedencies, libcircle fails to get past the checks for the 'mpicc --showme' option. This is because the Cray MPICH installation does not support this option. 

To get around this, I decided to install your package inside a Singularity Container. I have posted my container recipe here which reads much like a bash script in the '%post' section:

So I start by building a container with a working openmpi installation:

https://github.com/jtchilders/singularity_mpi_test_recipe/blob/master/Singularity.openmpi

Then I use the container build by this recipe as a base for your mpifileutils:

https://github.com/jtchilders/singularity_mpi_test_recipe/blob/master/Singularity.mpifileutils

You can see the build instructions in these recipes. The build proceeds without complaints, however, when I run 'dcp' inside the container I see this:

    ~/mpifileutils> dcp --help
    [2018-06-12T17:17:56] [0] [dcp.c:263] Exiting run

I have a test MPI C application in the same image which calculates 'pi' and it runs so I know it is not the MPI installation. 

Any suggestions why this might be failing?

**Comment by dsikich** [comment]
@jtchilders Do you happen to use spack? If so, there is an mpifileutils package added to it. Should simplify to "spack install mpifileutils." That is usually what we recommend unless you are planning to do development. I will also look more closely at your issue here. 

The mpifileutils package was recently updated, so I would use the latest version:
https://github.com/spack/spack

**Comment by jtchilders** [comment]
Thanks for the comments. We don't have Spack installed at the moment. I know someone is working on that, but they are having trouble installing it in the Cray environment.

I ran with mpirun to get the same output below. 

And just to elaborate a bit more my goal is to build mpifileutils inside the container against OpenMPI, then use the 'application binary independence' and swap out the libmpi.so with that from Cray on my supercomputer. I've done this in the past successfully. 


```
~/mpifileutils> mpirun -n 1 dcp
[2018-06-12T18:26:31] [0] [dcp.c:263] Exiting run
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[40434,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by adammoody** [comment]
Well that error message is a bit less than helpful, but it's coming from here:

https://github.com/hpc/mpifileutils/blob/16d42972d63a84934fd7c7c383199cafec72e2f2/src/dcp/dcp.c#L262

This shows up if it finds an error when processing the items on the command line.  That might be valid here, if you left --help off, but I don't know why it didn't print usage in the singleton case.

Can you try a different command like:    mpirun -np 1 dwalk --help

**Comment by jtchilders** [comment]
OK, that worked:

~/mpifileutils> mpirun -n 1 dwalk --help

Usage: dwalk [options] <path> ...

Options:
  -i, --input <file>                      - read list from file
  -o, --output <file>                     - write processed list to file
  -l, --lite                              - walk file system without stat
  -s, --sort <fields>                     - sort output by comma-delimited fields
  -d, --distribution <field>:<separators> - print distribution by field
  -p, --print                             - print files to screen
  -v, --verbose                           - verbose output
  -h, --help                              - print usage

Fields: name,user,group,uid,gid,atime,mtime,ctime,size

**Comment by adammoody** [comment]
I can reproduce the "Exiting run" with "dcp -h" in v0.7 here.  Looks like we fixed this in the master branch, which does print usage info.  We are working toward a v0.8 release in early August, so that will include this fix.

Anyway, I think you should have a working install.  Please let us know if you hit other issues.

**Comment by jtchilders** [comment]
OK, so I should then use the master branch instead of 0.7?

**Comment by adammoody** [comment]
It does contain some useful fixes over v0.7.  However, the master branch is changing / unstable as we merge commits to it.  Long term, I'd go with a stamped version so you know what you're getting on each build, but until we make the next release, you could build from master to pick up these fixes.

**Comment by dsikich** [comment]
@jtchilders Yeah, in this case since we haven't released an updated version in a while I would use the updated master branch until v0.8. If you hit anymore bugs let us know and we can submit a patch for them, which will ultimately improve v0.8.

**Comment by gonsie** [comment]
@jtchilders Hopefully v0.8 (and now v0.9) work for you. If you have any further issues please file a new issue. Thank you!
