### ISSUE TITLE
Improve dcp error messages

### ISSUE THREAD

**Issue by adammoody** [hpc/mpifileutils#132]
Let's tweak the dcp error reporting a bit.  First, in addition to the "exiting run", let's print a message about invalid source/destination parameters here so the user knows why the command is bailing out:

https://github.com/hpc/mpifileutils/blob/16d42972d63a84934fd7c7c383199cafec72e2f2/src/dcp/dcp.c#L262

And here, let's fix the English about missing source arguments, so that we give a complete phrase.  Also, let's not print that particular message when usage == 1, since in that case, the user gave us a --help and did not intend to run the command which is why the source args are missing:

https://github.com/hpc/mpifileutils/blob/16d42972d63a84934fd7c7c383199cafec72e2f2/src/dcp/dcp.c#L243

**Comment by adammoody** [comment]
Oh, and let's add a usage check on the front end of that if block so if they give us something like "dcp --help foo bar", we'll print the usage and exit.

**Comment by dsikich** [comment]
#134
