### ISSUE TITLE
Is dcp with input file broken?

### ISSUE THREAD

**Issue by deckard17** [hpc/mpifileutils#145]
Hello,

Testing with input file on master it seems like the format on the raw file is broken.

Generated the file with dcmp:

```
[morenod@eu-a6-012-22 ~]$ mpirun -np 4 dcmp  -o EXIST=DIFFER:/tmp/different.bin /cluster/scratch/morenod/sync_file1/ /cluster/scratch/morenod/sync_file2/
Files which exist only in one directory: [10/1], dumped to "/tmp/different.bin"
```
Then:

```
[morenod@eu-a6-012-22 ~]$ mpirun -np 4 dcp -vpS -i /tmp/different.bin /cluster/scratch/morenod/sync_file2/
[2018-08-17T16:27:37] [0] [dcp.c:186] Preserving file attributes.
[2018-08-17T16:27:37] [0] [dcp.c:198] Using sparse file
[2018-08-17T16:27:37] [0] [dcp.c:180] Using input list.
[2018-08-17T16:27:37] [0] [dcp.c:242] A source and destination path is needed
```

First of all it's not clear to me why do we need to specify a source path if we're already submitting an input file. I can create another ticket if you think it would be more useful to remove the need for a source target in case ```-i``` is used. 

Even submitting a source path it seems like the format is not what it's expecting:

```
[morenod@eu-a6-012-22 ~]$ mpirun -np 4 dcp -vpS -i /tmp/different.bin /cluster/scratch/morenod/sync_file1/ /cluster/scratch/morenod/sync_file2/
[2018-08-17T16:29:57] [0] [dcp.c:186] Preserving file attributes.
[2018-08-17T16:29:57] [0] [dcp.c:198] Using sparse file
[2018-08-17T16:29:57] [0] [dcp.c:180] Using input list.
Reading from input file: /tmp/different.bin
Read 0 files in 0.002866 seconds (0.000000 files/sec)
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:641] Creating directories.
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:865] Creating files.
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:1365] Copying data.
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:498] Setting ownership, permissions, and timestamps.
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:1481] Syncing updates to disk.
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:1542] Started: Aug-17-2018,16:29:57
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:1543] Completed: Aug-17-2018,16:29:57
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:1544] Seconds: 0.010
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:1545] Items: 0
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:1546]   Directories: 0
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:1547]   Files: 0
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:1548]   Links: 0
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:1550] Data: 0.000 B (0 bytes)
[2018-08-17T16:29:57] [0] [mfu_flist_copy.c:1554] Rate: 0.000 B/s (000 bytes in 0.010 seconds)
```

It looks to me like dcmp would try to store the file as version 2, as per ```write_cache_readdir```:

```
   /* prepare header */
    uint64_t header[5];
    header[0] = 2;               /* file version */
    header[1] = walk_start;      /* time_t when file walk started */
    header[2] = walk_end;        /* time_t when file walk stopped */
```

But maybe it's actually going through ```write_cache_readdir_variable``` instead.

In any case, the file is not recognized later by either ```read_cache_v3``` or ```read_cache_variable```.

Before further debugging I'd like to know if this is already known of there is a workaround that I could apply. I could not find anything related in the list of issues.

I also tried with v0.7 but there it's even not starting the read of the file...

I will attach the binary generated to this ticket.

**Comment by deckard17** [comment]
[file.zip](https://github.com/hpc/mpifileutils/files/2297640/file.zip)

**Comment by adammoody** [comment]
The output file I get from a similar test seems to have the correct format.  Can you tell whether the output file has any content after the dcmp command?

What do you see if you try to read and print the file through dwalk:

dwalk -v -p -i /tmp/different.bin

**Comment by adammoody** [comment]
Also, in this particular use case, it looks like you are trying to identify the set of files that exist in one directory that are not also in a second directory, and then you're trying to copy those files from the first over to the second directory.  If this is what you're looking for, let me know.

There is a synchronize option that may help.  We are about to release v0.8 which will contain a new "dsync" tool just for that purpose.  In v0.7, you can accomplish the same thing with "dcp -s /path/to/source /path/to/copy/of/source".  We may drop the "dcp -s" option in v0.8 and later, since that function is being moved to dsync.

**Comment by adammoody** [comment]
On first glance, the attached output file looks to be corrupted.  I wonder if the MPI I/O got scrambled or something.  Does it do better if you run the dcmp job with a single process?

**Comment by deckard17** [comment]
It didn't improve by running dcmp in a single process but I tested this with a newer version of MPI in another cluster and indeed, the v0.7 tag worked well.

So, I think this is an external problem to MPIFIleUtils. Thanks Adam for the hints!

**Comment by adammoody** [comment]
Can you share which MPI library and version you were using?  It might be good to know if we have a compatibility problem with MPI I/O in case it comes up again.

From my testing, I was seeing a second bug in dcmp + dcp in which it was trying to copy source files into the wrong path in the destination.  I need to investigate that further.  If you also see that, let's open a fresh ticket.

**Comment by deckard17** [comment]
I tried with Open MPI 1.6 and 1.8 and I had the same problem: dwalk was unable to read the binary.

When I swiched to Open MPI 2.1.1 I no longer had the issue and dwalk provided a proper output. Do not hesitate to ask if you need further information.

**Comment by diegolmoreno** [comment]
Note: just chagend username from deckard17 to diegolmoreno

I'm struggling to find the semantics of having an input file. At first I took it as a sort of replacement for the list of input files, so instead of saying ```dcp /path/file1 /path/file2 /dst_path/``` we could run ```dcp -i my_list.txt /dst_path/``` with my_list.txt containing obviously /path/file1 and /path/file2. 

On the usage of the command we read:
```
 -i, --input <file>  - read source list from file
```

Which would imply than need we don't need to provide the argument _source_. However having a source path is mandatory because if we have only the destination directory the run will failt:

```
        numpaths_src = numpaths - 1;
    }

    if (usage || numpaths_src == 0) {
        if(rank == 0) {
            if (usage != 1) {
                MFU_LOG(MFU_LOG_ERR, "A source and destination path is needed");
            }
```
So, what's the expected usage of the input file and would it make sense to open a ticket so we can improve the documentation?
