### ISSUE TITLE
dwalk: Add dynamically generated size histogram

### ISSUE THREAD

**Issue by daltschu22** [hpc/mpifileutils#205]
I believe the `--distribution` flag for size should generate a histogram automatically if the size distributions are not specified. 

For example, it could dump out a histogram of say, powers of 2.
I have a python tool that does filesystem analytics and it does this sort of a thing. So you just run the tool using the `--size-histogram` flag and it pops out a nice human friendly dictionary like:
      ```  'SizeHistogram': {   '1024KiB': 33,
                         '128KiB': 441,
                         '16KiB': 2292,
                         '16MiB': 2,
                         '1GiB': 2,
                         '1KB': 6142,
                         '1KiB': 1764,
                         '1MiB': 23,
                         '256KiB': 175,
                         '2KiB': 2853,
                         '2MiB': 13,
                         '32KiB': 1517,
                         '32MiB': 1,
                         '4KiB': 3434,
                         '4MiB': 6,
                         '512KiB': 100,
                         '64KiB': 943,
                         '8KiB': 2556,
                         '8MiB': 3},```

This dictionary grows dynamically with each new file no matter what the size is (Entries to the dictionary are added automatically when a file of that general size is found, and any new files have the count incremented). 

This makes it much easier to generate size histograms, as you dont need to think too much about the size ranges that you want if you just want a general overview.

**Comment by dsikich** [comment]
@daltschu22 Thanks for the feedback. These are not all in the same units. How is this program deciding whether to use say KB or MB as the units?

**Comment by daltschu22** [comment]
Basically the way it works is it gets the size of a file in bytes.
Then you convert that size into a human readable format. 
My code for that is here: 
https://github.com/daltschu22/crawlinator/blob/master/crawlinator.py#L152-L178

If that file is say, 16 Gibibytes, then it uses the "GiB" unit range, and then it finds the closest power of 2 to that file size. So 16 is already a power of 2 it adds a counter to the '16GiB' entry in the dictionary.
If you had say 

If that file is 150 Kibibytes, then round down to 128KiB and add a counter in that section of the dictionary.

The histogram generation is here:
https://github.com/daltschu22/crawlinator/blob/master/crawlinator.py#L132-L150

Does that make sense? I can explain further if need be.

**Comment by dsikich** [comment]
@daltschu22 Yep, makes sense. Thanks.

**Comment by daltschu22** [comment]
Wonderful work, thanks so much!
