### ISSUE TITLE
add checks for LLAPI to CMakeLists

### ISSUE THREAD

**Issue by adammoody** [hpc/mpifileutils#235]
Running a test with dstripe throws an error:
```
./install/bin/dstripe /path/to/file/on/lustre
Unexpected Lustre version.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
Need to complete our definition for various Lustre compile macros in our CMakeLists.txt:
```
OPTION(ENABLE_LUSTRE "Enable optimization and features for Lustre" OFF)
IF(ENABLE_LUSTRE)
  ADD_DEFINITIONS(-DLUSTRE_SUPPORT)
  # todo investigate usage of other lustre #defs
  # - LUSTRE_STAT
  # - HAVE_LUSTRE_LUSTREAPI_H
  # - HAVE_LUSTRE_LUSTRE_USER_H
ENDIF(ENABLE_LUSTRE)
```

**Comment by adammoody** [comment]
Here were the m4 checks, will need to find cmake equivalents:
https://github.com/hpc/mpifileutils/blob/v0.8.1/m4/lx_find_lustre.m4

**Comment by gonsie** [comment]
Thanks @adammoody. Let me see if I’m understanding the m4 correctly:
- it checks for `lustre/lustre_user.h` and `lustre/lustreapi.h` headers
- it adds `-llustreapi` to the link line
- it #defines LUSTRE_SUPPORT
- it checks for 3 functions(?) in the lustreapi library and #defines corresponding vars
  - `llapi_layout_alloc` => HAVE_LLAPI_LAYOUT
  - `llapi_file_create` => HAVE_LLAPI_FILE_CREATE
  - `llapi_file_get_stripe` => HAVE_LLAPI_FILE_GET_STRIPE

**Comment by adammoody** [comment]
@gonsie , m4 is always a mystery to me.  I'm interpreting it the same way.  It's possible the m4 macros have some other side effects, but I'm not sure if those are important.  For example, this page says that AC_CHECK_HEADERS defines some macros like HAVE_HEADERNAME:
https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Generic-Headers.html

And for AC_CHECK_LIB:
https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Libraries.html

**Comment by adammoody** [comment]
The code that's currently disabled is here:
https://github.com/hpc/mpifileutils/blob/97cabf759e2b4cbf3dad9984154897339e36b574/src/common/mfu_util.c#L861

It requires ```#ifdef LUSTRE_SUPPORT``` as a top-level check and then things like```#if defined(HAVE_LLAPI_LAYOUT)``` before calling the various functions.

**Comment by adammoody** [comment]
@gonsie , thanks for taking a look at this!

**Comment by adammoody** [comment]
Fixed with https://github.com/hpc/mpifileutils/pull/239
