### ISSUE TITLE
dbcast: fails on creating existing directory

### ISSUE THREAD

**Issue by gonsie** [hpc/mpifileutils#251]
A user had this issue:

> One thing I noticed a bit confusing is that dbcast seems to always try to create a new directory for the file to transfer, so this fails:
> `dbcast somefile.txt $BBPATH/somefile.txt`
> It fails since dbcast tries to create a directory $BBPATH, which already exists.
Instead, this works:
> `dbcast somefile.txt $BBPATH/test/somefile.txt`
> Here, $BBPATH/test does not exist, so creating the directory works.

**Comment by adammoody** [comment]
Yep, great point!

**Comment by gonsie** [comment]
fixed by #253
