### ISSUE TITLE
Allow setting to uid and gid in dchmod

### ISSUE THREAD

**Issue by cmharr** [hpc/mpifileutils#279]
Currently dchmod only appears to accept user and group names instead of numeric IDs. In the case where resolving a name is difficult (e.g. a LC CZ user that doesn't exist on RZ), it would be beneficial to be able to supply a UID or GID instead of a name.

**Comment by adammoody** [comment]
Good point!  That should be easy to add, too, so very good point :-)

**Comment by adammoody** [comment]
This PR adds support for giving numeric uid/gid in --owner/--group options:  https://github.com/hpc/mpifileutils/pull/280

**Comment by adammoody** [comment]
This feature was added with v0.10
