### ISSUE TITLE
fix problem with configure requiring export CC=mpicc in order to detect DTCMP

### ISSUE THREAD

**Issue by adammoody** [hpc/mpifileutils#33]
For the travisci build, we need to export CC=mpicc for configure to detect DTCMP.  Otherwise, it fails with undefined references to MPI symbols.

**Comment by gonsie** [comment]
I believe that this was fixed by changing the build system to cmake. In particular, this commit (7709f5816bcc1044a43911c7f602f77d1704a9eb) updated the travis build.
