### ISSUE TITLE
dchmod: proposed change to how --force works

### ISSUE THREAD

**Issue by noodle10000** [hpc/mpifileutils#330]
Hi,

If I have a set of files with permissions where most files are correct but a few aren't , it would be useful for --force to only try and change those files that don't match.  As it stands, you would need to use the --force option and I believe that will chown/chmod regardless.

This would be particularly useful if running dchmod via sudo or with the set_chown capability.  For example, the administrator could efficiently clean up files that users have created with overly permissive umasks.

I could probably come up with a diff if it's something of interest, but I wasn't sure if you prefer that --force remains as it is, and have a different option (--force-if-different) for this use case.

**Comment by adammoody** [comment]
Thanks for your suggestion, @noodle10000 , and the offer to contribute a patch.  We always welcome contributions.

Are you using the v0.10 release or something earlier?

In our latest release, I believe dchmod should only attempt to execute a chmod() on files that need to be changed.  By default, it should skip files that already have correct permissions, unless one sets the --force option or if dchmod doesn't have the existing permissions to check against.  The logic for that is here:

https://github.com/hpc/mpifileutils/blob/20ff7e4c01cf7e346cd59b001719068014087bfa/src/common/mfu_flist_chmod.c#L1028

Looking at that again now, I do see if one is running as root, I guess one has to run with --force to get it to change permissions at all for any file not owned by root.

https://github.com/hpc/mpifileutils/blob/20ff7e4c01cf7e346cd59b001719068014087bfa/src/common/mfu_flist_chmod.c#L1062

Maybe we need a way to detect if the current user has ability to change permissions and still try?

**Comment by adammoody** [comment]
Taking a lead from:

https://stackoverflow.com/questions/43599961/test-for-linux-cap-fowner-capability-in-c

Maybe libcap and CAP_IS_SUPPORTED(CAP_FOWNER) would work:

http://man7.org/linux/man-pages/man3/cap_get_proc.3.html

**Comment by adammoody** [comment]
@noodle10000 , I'll look at adding a patch for this soon.  Would you be willing to test it out from a branch?

**Comment by noodle10000** [comment]
Hi - sorry for late response.  Yep I can test this.

**Comment by adammoody** [comment]
Thanks, @noodle10000 .  Should be ready to test now.  The work is on PR https://github.com/hpc/mpifileutils/pull/331

The intent is that by default, now even when running as root, dchmod should attempt to change permissions on files if they are different and skip any file that already has the correct permissions.  As before, the --force option can be used to execute chmod() on every file, regardless of its current permissions.

**Comment by noodle10000** [comment]
Thanks!  FWIW, I tested just now (by setting the capabilities on the the dchmod binary with `setcap cap_chown+ep /bin/dchmod`) and seems to work just fine in our environment.

**Comment by adammoody** [comment]
Great, thanks for verifying that fix, @noodle10000 .  We're planning a v0.10.1 release soon, so this will be picked up in that.
