### ISSUE TITLE
feeding binary cache file from dfind or dwalk to drm causes seg fault

### ISSUE THREAD

**Issue by brockpalen** [hpc/mpifileutils#337]
Tried with both 0.10  and current master.  Same behavior.  Host is Centos 7

 1) gcc/8.2.0   2) openmpi/4.0.3   3) cmake/3.13.2

Trying to build lists of files for scratch purge and I'm having trouble passing data between tools like dfind and dwalk.  I notice if I strings the cache file it's storing much more data than the single entry my test data should.  Though not knowing the format not sure but I'm seeing file paths outside the path i'm running in.   If I use text output or print to screen the results are what I would expect.

`mpirun -np 4 ~/mpifileutils/build/src/dwalk/dwalk --output  /tmp/output  -p .`
```
 mpirun -np 4 ~/mpifileutils/build/src/drm/drm --input /tmp/output --dryrun
[2020-05-24T20:14:01] Reading from input file: /tmp/output
[gl-login1:58972:0:58972] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace (tid:  58972) ====
 0 0x0000000000010e52 mfu_flist_compute_depth()  ???:0
 1 0x0000000000021efd list_elem_decode()  mfu_flist_io.c:0
 2 0x0000000000022325 list_insert_decode()  mfu_flist_io.c:0
 3 0x0000000000022838 read_cache_variable()  mfu_flist_io.c:0
 4 0x0000000000023ea7 mfu_flist_read_cache()  ???:0
 5 0x0000000000401d18 main()  ???:0
 6 0x0000000000022505 __libc_start_main()  ???:0
 7 0x00000000004013c9 _start()  ???:0
=================================
```

**Comment by adammoody** [comment]
Thanks for the report, @brockpalen .

Strange that it would fail in that function.  This traverses a string counting '/' characters:
https://github.com/hpc/mpifileutils/blob/57a3578b68d8df0fa53a7662c33c6c21ce72400f/src/common/mfu_flist.c#L106
Are you able to catch a debug build under a debugger?

How many items are in your cache file?

Is that something you could send to me?

**Comment by adammoody** [comment]
So another clue I see in your dwalk command and stack trace.  That dwalk command *should* have created a binary file.  However, from the stack trace, it's trying to read it with ```read_cache_variable()```, which means it didn't understand the version number in the header of the file, which is the first 8 bytes of the file:
https://github.com/hpc/mpifileutils/blob/57a3578b68d8df0fa53a7662c33c6c21ce72400f/src/common/mfu_flist_io.c#L1046

Can you do a hexdump of the header?

I see something like this:
```
>>: hexdump -C -n 32 list.mfu
00000000  00 00 00 00 00 00 00 04  00 00 00 00 00 00 07 61  |...............a|
00000010  00 00 00 00 00 00 00 18  00 00 00 00 00 00 0b 30  |...............0|
```
Those first 8 bytes should have version=4 (```00 00 00 00 00 00 00 04```).

**Comment by brockpalen** [comment]
Sure,  looks like as much as it's binary it starts with a string.  Weird. 

` mpirun -np 4 ~/mpifileutils/build/src/dfind/dfind --user brockp --output /tmp/output .`

```
[brockp@gl-login1 support]$ hexdump -C -n 32 /tmp/output 
00000000  2f 67 70 66 73 2f 61 63  63 6f 75 6e 74 73 2f 61  |/gpfs/accounts/a|
00000010  72 63 5f 74 73 5f 72 6f  6f 74 2f 73 75 70 70 6f  |rc_ts_root/suppo|
00000020
```

I'm happy to send an example cache file to you.  My test version is 1.2MByte and it's all metadata that is not protected (test data).

**Comment by adammoody** [comment]
It looks like the beginning portion of the file is not there or has been overwritten.  Can you reproduce the same problem if you write the file from dwalk running with a single MPI task?

**Comment by brockpalen** [comment]
Exact same behavior
`/tmp/`  is a local drive in the host

` mpirun -np 1 ~/mpifileutils/build/src/dfind/dfind --user brockp --output /tmp/output . `

```
[2020-05-26T19:52:30] Walking /gpfs/accounts/arc_ts_root/support
[2020-05-26T19:52:40] Walked 27431 items in 10.015459 secs (2738.865889 items/sec) ...
[2020-05-26T19:52:50] Walked 52583 items in 20.015119 secs (2627.164036 items/sec) ...
[2020-05-26T19:53:00] Walked 85989 items in 30.016495 secs (2864.724916 items/sec) ...
[2020-05-26T19:53:10] Walked 126325 items in 40.016214 secs (3156.845366 items/sec) ...
[2020-05-26T19:53:20] Walked 178625 items in 50.016384 secs (3571.329713 items/sec) ...
[2020-05-26T19:53:23] Walked 196145 items in 52.830384 secs (3712.730891 items/sec) ...
[2020-05-26T19:53:23] Walked 196145 items in 52.843414 seconds (3711.815414 items/sec)
[2020-05-26T19:53:23] Writing to output file: /tmp/output
[2020-05-26T19:53:23] Wrote 4563 files in 0.003196 seconds (1427770.847004 files/sec)
[brockp@gl-login1 support]$ hexdump -C -n 32 /tmp/output 
00000000  2f 67 70 66 73 2f 61 63  63 6f 75 6e 74 73 2f 61  |/gpfs/accounts/a|
00000010  72 63 5f 74 73 5f 72 6f  6f 74 2f 73 75 70 70 6f  |rc_ts_root/suppo|
00000020
```

**Comment by adammoody** [comment]
Ok, that tells us that it's not due to different MPI ranks clobbering each other while writing the file.  Let me check the write path again.

**Comment by adammoody** [comment]
I have Open MPI 4.0.0 installed on a cluster.  I found this hangs when writing an output file to my home directory, which is an NFS mount.  Under a debugger I can see it is stuck trying to lock a file.  That's not directly related to your issue, but figured I'd mention that in case you also see that.

Anyway, this Open MPI install is using OMPIIO for its MPI I/O by default.  It lets me switch to use ROMIO instead:

```mpirun -np 128 --mca io romio321 ...```

In my case, that got past the hang and wrote a valid file.  I think that's worth a shot in your case as well.

Can you try that?

Also what type of file system is your /tmp -- what does ```df /tmp``` report?

**Comment by brockpalen** [comment]
Actually that worked. Telling OMPI to use romio rather than OMPI fixed the issue.

Note I have to use romio321 to read the data into `drm` but it works.

`/tmp` is a normal device mapper local disk in the node  (ranks are only on that node)
```
[brockp@gl-login1 purge-test]$ df -h /tmp/
Filesystem                  Size  Used Avail Use% Mounted on
/dev/mapper/arcts_rust-tmp  3.6T   38G  3.5T   2% /tmp
```

```
mpirun --mca io romio321  -np 1 ~/mpifileutils/build/src/dfind/dfind --user brockp --output /tmp/output .

mpirun --mca io romio321 -np 4 ~/mpifileutils/build/src/drm/drm --dryrun --input /tmp/output --output /tmp/rm-log
```

worked as expected.

Should I open an issue with the OMPI team?

**Comment by adammoody** [comment]
Ok, good to know that works.  I suspect there may be a bug in the MPI I/O layer here, but let me dig further into it before we open a ticket with Open MPI.

**Comment by brockpalen** [comment]
Following up,  Happy to open a request with the OMPI team if we think there is an issue with OMPI MPI-IO IO module.

**Comment by adammoody** [comment]
Thanks, @brockpalen .  I'll take a look at the MPI I/O calls we're making just to double check that I think we're using the API correctly, then we can open a ticket with Open MPI.  Trying not to bother them if it's due to a bug on our part.

**Comment by adammoody** [comment]
I had a chance to dive into the Open MPI 4.0.3 code today.  The good news is that I can reproduce the same behavior you are seeing with that version.  The bad news is that OMPIO doesn't seem to have support for "external32" format yet.

They look to be bailing out from at least some of the MPI I/O calls with an error, which is good.  However, we're not checking the return codes from the MPI I/O calls in mpiFileUtils.

From the mpiFileUtils side, I'll add some error checks in there.  We should at least be able to catch that and report an error to the user.

We can also think about allowing the user to specify a different MPI file format.  For example, I think "native" format works with OMPIO.  However, that file format can be anything the MPI library wants to use, which means we don't have control over the bits in the file.  That's a problem when you're trying to write to a particular binary file format.  We use "external32" in mpiFileUtils, because that format is supposed to be standardized, which lets it work across MPI libraries and also lets one write a known binary format so non-MPI programs can read and write the file.

**Comment by adammoody** [comment]
Funny story...  I ran into problems with "external32" a while back.  The "external32" data representation is *supposed* to write out data in the same format no matter what MPI library you use.  The exact format specification is defined in the MPI standard.

I found that IBM Spectrum MPI, MPICH/MVAPICH, and Open MPI each produced a different binary file with "external32" when writing out a particular derived datatype.  They should have all produced identical binary files!

What's worse is that none of them actually followed the format that is defined in the standard.  So none of them were right, but they all messed it up in different ways.  I ended up filing bug reports with all of them.

Open MPI at least said they would detect that and return an error, which they are doing now.
https://github.com/open-mpi/ompi/issues/5643

Hooray for standards that no one follows!

As a result I decided to do all data management directly, so the code now does all data conversion internally and then just writes bytes.  Now that I think about it, I might be able to make a full switch to "native".  If I'm using MPI_BYTE everywhere, it's hard to imagine anyone's "native" format messing with a byte.  I'll consider that and try to get one of these fixes in by early next week.

**Comment by adammoody** [comment]
@brockpalen , I've got a PR started here https://github.com/hpc/mpifileutils/pull/342.  I think it should fix the problem you found with Open MPI 4.0.3, so that both romio321 and the default ompio module should work.  I added some error checks about the MPI I/O code, which would have caused it to throw an error message when MPI_File_set_view returned the error we weren't catching before.  However, I also changed from external32 to native.  I'm hoping "native" will be more portable across MPI libs.

I'd like to fix the problem you're seeing with sorting an empty list.  Investigating that now.

**Comment by adammoody** [comment]
Updated the PR with a commit to fix sorting on empty lists.

**Comment by brockpalen** [comment]
This does appear fixed in the latest builds,

**Comment by adammoody** [comment]
Thanks, @brockpalen .  BTW, I haven't forgotten about your PR.  Hoping to swing back to that soon.
