### ISSUE TITLE
mpifileutils using old mechanism for querying lustre striping of file

### ISSUE THREAD

**Issue by ofaaland** [hpc/mpifileutils#340]
Run dwalk on a lustre 2.10 or 2.12 client.
The lustre client's console log reports this warning:

```
2020-06-02 13:21:48 [2265774.790703] Lustre: dwalk: using old ioctl(LL_IOC_LOV_GETSTRIPE) on [0x50003e49e:0x3:0x0], use llapi_layout_get_by_path()
```

The recommended interface, llapi_layout_get_by_path(), is available in Lustre >= 2.7.0.  See llapi_layout(7) for details.

mpifileutils should switch to using it.

I don't recall how it works, but I recall there being some mechanism to prevent this message from being emitted repeatedly.  Testing an mpifileutils change repeatedly may require use of a unique file each time, or umount and remount the lustre client to clear a flag.

**Comment by adammoody** [comment]
Thanks, @ofaaland .  I'm trying to remember why dwalk would be making a call about lustre striping.

What version of mpiFileUtils were you using here?

Did you specify any command line options?

**Comment by ofaaland** [comment]
Hi @adammoody , sorry for missing such basic information in the bug report.  I'll reproduce it and get you more complete information.

**Comment by adammoody** [comment]
Hi @ofaaland , did you get a chance to investigate this further?  If it's within mpiFileUtils, we'll fix it.  It's possible it might be coming from within MPI I/O, in which case, I'd like to forward this on to the MPI I/O developers.  I might have to work with you to narrow that down.

**Comment by ofaaland** [comment]
Hi Adam,

No, I forgot, thanks for the reminder.  I'll get back to you soon.

-Olaf

________________________________________

**Comment by ofaaland** [comment]
Hi Adam,

I'm unable to reproduce the issue with mpifileutils-0.10 (most recent in TCE as far as I can tell on oslic).  I see via nm that libmfu.so is using the correct function, llapi_layout_get_by_path().  I think I must have been using an old version, sorry for the bad report.

Closing this issue.
