### ISSUE TITLE
daos: double check errors in daos_read/write

### ISSUE THREAD

**Issue by adammoody** [hpc/mpifileutils#350]
I think our daos_read() and daos_write() have a couple of things to fix.

We are setting ```rc = -1``` here on errors, but then we return ```got_size``` no matter what.
https://github.com/hpc/mpifileutils/blob/a059f299c3b0d4f4409a0ce48360a1081645d1b4/src/common/mfu_io.c#L793

Also, we're updating the offset, even on error cases.  Not sure if that's correct to do or not (depends on got_size).
https://github.com/hpc/mpifileutils/blob/a059f299c3b0d4f4409a0ce48360a1081645d1b4/src/common/mfu_io.c#L795

**Comment by dsikich** [comment]
@adammoody so it looks like I should be turning the got_size for daos_read on error, and return -1 on error for daos_write? According to the man page for read it is ok to return the got_size without updating the offset?

**Comment by adammoody** [comment]
I think this is what you're saying, but let's set up the daos_read and daos_write wrappers to behave like the following:
```
dfs_read/write()

// on error, do not update file pointer, but set errno and return -1
if (error) {
  errno = (error code);
  return -1;
}

// no error, so the read/write succeeded but perhaps with less bytes than requested,
// update file pointer and return number of bytes actually read/written
file->offset += num_bytes;
return num_bytes;
```
Checking the read(2) man page I see that it says on error, it's undefined as to what happens to the file pointer.  That means in the error case, we could chance the file pointer if we wanted.  However, I like the approach here since read and write behave the same way.
