### ISSUE TITLE
daos: move sgl and iov variables to daos_read/write

### ISSUE THREAD

**Issue by adammoody** [hpc/mpifileutils#351]
Let's move the sgl and iov variables to be local variables inside of the daos_read/write functions.  I think we can set these based on the params passed into those functions.

https://github.com/hpc/mpifileutils/blob/a059f299c3b0d4f4409a0ce48360a1081645d1b4/src/common/mfu_flist_copy.c#L1624

After that, I think we should only have ```buf``` left for the DAOS-specific part in ```mfu_copy_file_normal```.

**Comment by dsikich** [comment]
@adammoody it does look like I will need to add but_size as a parameter to these functions as well as mfu_file_read/write, does that sound good?

**Comment by adammoody** [comment]
I was wondering about that, too.  Do you know whether it safe to use ```size``` in the case to ```d_iov_set``` instead of ```buf_size``` so long as you know that ```size < buf_size```?  If so, inside of the daos_read/write calls, we could change this to:
```
d_iov_set(&iov, buf, size);
```

**Comment by dsikich** [comment]
@adammoody I think it should be ok, but I will have to check to make sure.
