### ISSUE TITLE
dsync silently skipping directories that can't be opened (EACCES)

### ISSUE THREAD

**Issue by noodle10000** [hpc/mpifileutils#356]
Hello,

For directories that we are denied permission to, dsync does not generate an error (i.e. it's silently skipped).

I think it's as simple as updating walk_readdir_process_dir() and walk_stat_process_dir() to add the appropriate MFU_LOG message to the part that says:

    if (! dirp) {
        /* TODO: print error */
    }

(at least, that works for my use-case)

Thanks

Craig.

**Comment by daltonbohning** [comment]
This looks simple enough, and it will also help in DAOS, so I will add some error logging here.
