### ISSUE TITLE
Add llapi calls to dstripe report current Lustre striping of file

### ISSUE THREAD

**Issue by adammoody** [hpc/mpifileutils#37]
Let's add a --report option or something like that so that dstripe --report <file> will report the current striping of a file.

**Comment by adammoody** [comment]
Thanks, @dinatale2 Would you also please update the markdown pages in /doc which we use to generate the man pages?

**Comment by dinatale2** [comment]
@adammoody Updated the markdown. Let me know if it looks ok. If you are happy with what I have, I can go ahead and open a pull request.
