### ISSUE TITLE
Tweak dstripe so that it renames target file to source file after copy

### ISSUE THREAD

**Issue by adammoody** [hpc/mpifileutils#38]
Currently the user must provide a temporary name, delete the source, and then rename the target after restriping a file.  It would be nice to do this automatically, and this kind of feature will be especially useful when recursively restriping files in a directory tree.

**Comment by dinatale2** [comment]
@adammoody I just realized that there are mfu functions for operations such as deleting a file. I'll go back and use those instead and I'll add new mfu functions for the operations that don't exist.

**Comment by dinatale2** [comment]
Updated dstripe to use mfu functions where appropriate. Let me know if you notice anything else that needs to change. I can also open a pull request if you'd like to do a formal review.

**Comment by adammoody** [comment]
Hi Joe,
This looks good.  There may be one MPI-related bug.  I see you use rank 0 to generate the temp name for the destination file, and I see you're bcasting the temporary name.  However, it looks like the bcast is inside of an if statement that only rank 0 calls, so the other procs will not see the file name.  You'll want to move this bcast outside of the if block.  Let's break this into two sections, one if block where rank 0 computes the name, then a global region to bcast the name, then another if block where rank 0 creates the file.

Go ahead and open a pull request.

Thanks!
-Adam
________________________________________
