### ISSUE TITLE
daos: mfu_io: enhance lookup_insert_dir

### ISSUE THREAD

**Issue by daltonbohning** [hpc/mpifileutils#384]
Within `mfu_io` there is a function `lookup_insert_dir` that uses a hash table to speedup the lookups of DAOS container directories. 

1. Currently, this is only used when only the src is DAOS or only the dst is DAOS. We should make some modifications that allow it to be used when both the src and dst are DAOS.

2. The `fprintf(stderr, ...)` calls should be updated to `MFU_LOG(MFU_LOGG_ERR, ...)`.

3. We need to find the proper way to add a corresponding `d_hash_table_destroy` call to handle cleanup.

4. We should investigate the possibility of using the hash table(s) elsewhere. Any of the `daos_*` IO functions could potentially be candidates.

Mirrored DAOS Jira ticket:
https://jira.hpdd.intel.com/browse/DAOS-5722

**Comment by daltonbohning** [comment]
@dsikich

### Rough Proposal
**Step-by-step explanation**
1. There is a 1:1 relationship between a DAOS container and a `dfs` mount (the way we are using it, anyway).
2. Each container should have its own `d_hash_table` to avoid conflicts.
3. The `dfs` is stored with the `mfu_file` record.
4. We need to pass the `mfu_file` to `lookup_insert_dir` to get the `dfs`.
5. We can add a new entry `mfu_file_t->dir_hash` to hold the hash for that corresponding `dfs`.
6. When we call `dfs_mount`, we can also set the corresponding `mfu_file_t->dir_hash`.
7. We can create a wrapper function for this, for simplicity and reusability.
8. When we call `dfs_umount`, we can cleanup the `mfu_file_t->dir_hash`.
9. We can create a wrapper function for this as well, to keep the creation and destruction of the hash in sync.
10. At this point, each `mfu_file_t` would "automatically" have a `mfu_file_t->dir_hash`.
11. Now to utilize it...
12. All `dfs_lookup` calls within `mfu_io` are _similar_ (permissions, etc.) except for one that also passes `mode`, but ignore this for now.
13. We can replace _**all**_ `dfs_lookup` calls with a call to `lookup_insert_dir`.
14. `lookup_insert_dir` would get/insert into the corresponding `mfu_file->dir_hash`.
15. Now all lookups will use the hash.
16. This also has other (positive) implications.
17. The `dir_hash` will now be cleaned up properly (currently isn't) when we call `dfs_umount` (in our new wrapper function).
18. We can remove the `dfs_release` calls that I just added for each `dfs_lookup`, since cleanup is now centralized.

Please let me know how you feel about this, and if you see any potential issues. I'm not going to start working on this until I'm sure it will be robust, so I'm also going to think on it for a bit.

**Comment by dsikich** [comment]
@daltonbohning I don't think you can completely replace the dfs_lookup calls with the lookup_insert_dir. It should be that if the entry is not already in the hash table, then do a dfs_lookup. Since you will need to execute a lookup the first time that item is looked up, and any later lookups of that same item would be cached by the hash table.

**Comment by daltonbohning** [comment]
@dsikich Right. To clarify, this is what `lookup_insert_dir` would look like (and currently does):
```
lookup_insert_dir(name)
    if name is in hash:
        return hashed value
    
    val = dfs_lookup(name)
    store val in hash
    return val
```

So, there will be **_one_** `dfs_lookup` call in total, which would reside in `lookup_insert_dir`.
The idea is that this would also allow things like `daos_mknod`, `daos_stat`, `daos_open`, etc. to all share the same cached values.
I.e. if you call `daos_stat(somePath)`, then call `daos_open(somePath)`, then `daos_open` would use the cached value.

**Comment by dsikich** [comment]
@daltonbohning Ah ok. Yes, exactly. The lookup can be expensive for large file trees since DFS has to iterate over all entries from the root of the filesystem, so using the cached value will definitely help those functions avoid that.

**Comment by daltonbohning** [comment]
@dsikich Great! I'm not starting on this just yet, but when I do, I'll let you know if I hit any snags.
