### ISSUE TITLE
daos: abstract to daos_util

### ISSUE THREAD

**Issue by daltonbohning** [hpc/mpifileutils#391]
As we add more DAOS-related code, it would be a good idea to abstract as much as possible to a new `daos_util.[h,c]`.
Since we might be adding DAOS support to `dsync`, it would be a good idea to do this first, so `dsync` can reuse the code.

There are also plans to move the daos_* IO functions internal to DAOS, so we an leave those within `mfu_io` for now.

Some considerations:
- `daos_*` hash and helper functions within `mfu_io.c`
  - Maybe these could be moved to `daos_util.c`
- `daos_*` functions within `mfu_util.c`
  - These could be moved to `daos_util.c`
- `daos_*` functions within `dcp.c`
  - Some of these can be moved to `daos_util.c`
  - Some of these can be re-written in a way that they can be moved to `daos_util.c`
  - Some of the `dcp`-specific DAOS functions should probably remain in `dcp.c`

**Comment by daltonbohning** [comment]
@adammoody Would you prefer the `daos_*` functions in `mfu_io` be moved to a separate file as well?
For example, this is the pattern for each IO function:
```
mfu_file_op();  // Wrapper for DAOS vs POSIX type
mfu_op();       // POSIX op
daos_op();      // DAOS op
```
So, these are the three possible locations for the `daos_op` functions:
- `mfu_io` (current)
- `daos_util` (future daos utility file)
- `daos_io` (future daos IO file?)

**Comment by adammoody** [comment]
Yeah, I was wondering about that, too.  I think that's a good idea.

**Comment by daltonbohning** [comment]
As usual, thanks again!

**Comment by daltonbohning** [comment]
The daos I/O functions in mfu_io will eventually be moved internal to daos, so there is no need to move these to a "daos_io", etc.
