### ISSUE TITLE
mfu_flist_chunk.c: memory leak

### ISSUE THREAD

**Issue by daltonbohning** [hpc/mpifileutils#392]
None of these MALLOCs have a corresponding `mfu_free`:

https://github.com/hpc/mpifileutils/blob/66c5273035396c34998c32e9d7918bce9aeca58f/src/common/mfu_flist_chunk.c#L95-L96

https://github.com/hpc/mpifileutils/blob/66c5273035396c34998c32e9d7918bce9aeca58f/src/common/mfu_flist_chunk.c#L127-L131

**NOTE:** A pointer to each `elem` is stored in both `heads` and `tails`
https://github.com/hpc/mpifileutils/blob/66c5273035396c34998c32e9d7918bce9aeca58f/src/common/mfu_flist_chunk.c#L190

https://github.com/hpc/mpifileutils/blob/66c5273035396c34998c32e9d7918bce9aeca58f/src/common/mfu_flist_chunk.c#L252

https://github.com/hpc/mpifileutils/blob/66c5273035396c34998c32e9d7918bce9aeca58f/src/common/mfu_flist_chunk.c#L263-L264

https://github.com/hpc/mpifileutils/blob/66c5273035396c34998c32e9d7918bce9aeca58f/src/common/mfu_flist_chunk.c#L270-L271

https://github.com/hpc/mpifileutils/blob/66c5273035396c34998c32e9d7918bce9aeca58f/src/common/mfu_flist_chunk.c#L300

https://github.com/hpc/mpifileutils/blob/66c5273035396c34998c32e9d7918bce9aeca58f/src/common/mfu_flist_chunk.c#L329

\
\
The only MALLOC in this function that should _**not**_ be freed is:
https://github.com/hpc/mpifileutils/blob/66c5273035396c34998c32e9d7918bce9aeca58f/src/common/mfu_flist_chunk.c#L371
Since the `free` is done in `mfu_file_chunk_list_free`

**Comment by adammoody** [comment]
Nice.  Thanks for tracking these down.
