### ISSUE TITLE
libmfu: make the shared library versioned

### ISSUE THREAD

**Issue by brianjmurrell** [hpc/mpifileutils#396]
Looking at the files that are produced from the build I see:

```
/usr/lib64/libmfu.a
/usr/lib64/libmfu.so
```

The shared library looks unversioned.  There should be a libmfu.so._x_._y_ where the _x_ and _y_ are a version for the shared library, where the major version component (_x_) denotes ABI breakage that is non-backwards compatible.

Should this shared library be versioned as such?

**Comment by daltonbohning** [comment]
I'm not very familiar with `cmake` myself, but I thing we would need something like this:
https://cmake.org/pipermail/cmake/2012-September/051904.html

We would want to put that here:
https://github.com/hpc/mpifileutils/blob/fb5b43cd703bdf4d2857238fb5969525e688242b/src/common/CMakeLists.txt#L42-L48

**Comment by adammoody** [comment]
I think it's a good idea to version the library.  Right now, it's really only the self-packaged tools that use the library.  But there might be external tools people have built and eventually user applications might also include calls, both of which will make versioning more important.  We'll have to develop a habit to remember to bump the version number on ABI-breaking changes.

Thanks for looking up the steps, @daltonbohning .  Willing to submit a PR to add that?

**Comment by daltonbohning** [comment]
@adammoody Absolutely. I hope to get something either this evening (PST) or tomorrow morning.

@brianjmurrell Let me know anything else that might need to be done to get mpifileutils into an rpm for DAOS.

**Comment by daltonbohning** [comment]
@adammoody The last released version was `0.10.1`, released on Jul 6. There have been several changes since then, including DAOS support. What would you like the initial version to be set to in cmake? `0.11.0`?
(I also don't think there are any breaking changes)

**Comment by adammoody** [comment]
Yes, I'm thinking we'll tag the next release as v0.11.0.

**Comment by brianjmurrell** [comment]
Be sure not to confuse the version of the library (the ABI more precisely) and the overall version of the package.

For example, the version of the package can increase (many times even), perhaps because something in one of the binaries change, but the version of the library stays the same among those many package versions, because nothing in the library (ABI) has changed.

The version of the library should (only) change when new ABI changes are made.  If new functions are added, the minor version of the library is increased.  If functions are removed, or their signatures are changed, then the major version has to be increased.

**Comment by daltonbohning** [comment]
@brianjmurrell Thank you for that explanation; I was confusing the package version with the library version, which I think we should not do.
@adammoody Based on @brianjmurrell 's explanation, I think maybe we should start the `libmfu` binary version at `0.0.0`?
Then, the release version of the _**library**_ `libmfu` would be based on the changes within `src/common/`, since that is what is compiled into `libmfu`.
And the release version of the _**package**_ `mpifileutils` would be based on the change of the utilities/binaries.
