### ISSUE TITLE
daos: xattr support

### ISSUE THREAD

**Issue by daltonbohning** [hpc/mpifileutils#404]
**Wrapper `xattr` IO functions:**
- `mfu_file_llistxattr`
- `mfu_file_lgetxattr`
- `mfu_file_lsetxattr`

**Corresponding `daos_*` IO functions:**
- `daos_llistxattr`
- `daos_lgetxattr`
- `daos_lsetxattr`

**Corresponding POSIX IO functions:**
- `mfu_llistxattr`
- `mfu_lgetxattr`
- `mfu_lsetxattr`

**Update raw `xattr` functions**
- `mfu_flist_copy.c`
- Others TBD

**Error messages**
I noticed a few of the error messages for the `xattr` calls in `mfu_flist_copy.c` refer to the wrong function. For example, this message is for a `lgetxattr` call. We might as well correct this in the process.
https://github.com/hpc/mpifileutils/blob/4ec784108d066abe5060ebb197c1dba83e88bd7d/src/common/mfu_flist_copy.c#L309

**Comment by akesandgren** [comment]
There is the same llistxattr typo for the lsetxattr too, but i guess you know that already.

**Comment by daltonbohning** [comment]
> There is the same llistxattr typo for the lsetxattr too, but i guess you know that already.

Correct, #406 corrects this for `lsetxattr` and `lgetxattr`
(Pending)
