### ISSUE TITLE
dcp: User ID and Group ID

### ISSUE THREAD

**Issue by NateThornton** [hpc/mpifileutils#537]
As part of Near Node Flash (NNF) Data Movement implementation, there is the need to specify the User ID and Group ID when running dcp (explained [here](https://github.com/NearNodeFlash/nnf-dm/issues/30#issuecomment-1206798489)). 

For dcp, this work seems pretty straightforward to add with `-U [uid]` and `-G [gid]`.

For example
`dcp -U 1001 -G 1002 file.in file.out`

Does this work for everyone? Any other comments before I begin?

**Comment by bdevcich-hpe** [comment]
I created PR for this: https://github.com/hpc/mpifileutils/pull/540.

**Comment by ofaaland** [comment]
Fixed by Blake's PR #540 which was merged.
