### ISSUE TITLE
POS36-C. Observe correct revocation order while relinquishing privileges

### ISSUE THREAD

**Issue by brianjmurrell** [hpc/mpifileutils#567]
While running a linter (`rpmlint`) on the results of a build we are getting an error that refers to [POS36-C. Observe correct revocation order while relinquishing privileges](https://wiki.sei.cmu.edu/confluence/display/c/POS36-C.+Observe+correct+revocation+order+while+relinquishing+privileges) for `dcp`.

Is that actually a problem or is it a false-positive of some sort?

**Comment by brianjmurrell** [comment]
I should have noted that the particular issue that `rpmlint` was complaining about was not calling `setgroups()` before calling `setuid()`, to relinquish any elevated group privileges that are not wanted/necessary after the `setuid()`.

**Comment by daltonbohning** [comment]
@brianjmurrell I'll run a sample through our linter to see if I can fix this

**Comment by daltonbohning** [comment]
I ran #569 through our linter and it does resolve the warnings.
