### ISSUE TITLE
dsync deletes destination files after getting errors while walking the source

### ISSUE THREAD

**Issue by defaziogiancarlo** [hpc/mpifileutils#587]
I've seen multiple instances of dsync reporting errors while walking the source tree. In this case they are "transport endpoint shutdown" error on lustre due to clients being evicted from some of the OSTs. At the end of the source walk, the number of items reported is incorrect, and much lower than it should be due to the errors during the walk. Then, after the walking the destination, dsync determines that they are many excess items on the destination and deletes them. However, those items are not excess, they were just not found on the source due to the errors.

My suggestion for a solution is to do what rsync does, which is to not delete things on the destination if there were errors while reading the source, even if the --delete flag is specified.

v0.11.1
this is running on TOSS 4, which is based on RHEL using the 4.18.0-553.22.1 kernel
I'm actually not sure which mpi it was compiled with
I can't provide logs, but I'll try to reproduce this in an environment where I can provide the logs

**Comment by ofaaland** [comment]
> I can't provide logs, but I'll try to reproduce this in an environment where I can provide the logs

No need.  Eric can do that himself :)

**Comment by ofaaland** [comment]
@defaziogiancarlo please see https://github.com/hpc/mpifileutils/pull/599
