### ISSUE TITLE
dcmp: support light-weight meta data comparison

### ISSUE THREAD

**Issue by adammoody** [hpc/mpifileutils#59]
Like rsync, let's add a mode to dcmp --sync where we can assume the source and target files are identical if their sizes and mod times are the same, but different otherwise.  In this mode, we can avoid reading the full contents of each file.

We could perhaps use this mode by default, again like rsync, and execute the full check if the user throws an additional option.

**Comment by adammoody** [comment]
The --sync logic was moved to dsync, but it'd still be useful to have a light-weight compare option here, that only checks metadata.  Perhaps that can be constructed via a long command:

SIZE=COMMON@MTIME=COMMON@ATIME=COMMON...

However, that could be cumbersome.

**Comment by gonsie** [comment]
Done
