### ISSUE TITLE
sphinx generates \(aq for '

### ISSUE THREAD

**Issue by ofaaland** [hpc/mpifileutils#591]
When .rst files have an apostrophe, sphinx generates "\aq" in its place in the corresponding man page.

Observed with:
mpifileutils tag v0.11.1
sphinx 5.3.0
python 3.6

For example, in doc/rst/dcp.1.rst text
```
   Do not follow symbolic links in source paths. Effectviely allows
   symbolic links to be copied when the link target is not valid
   or there is not permission to read the link's target.
```
generates
```
Do not follow symbolic links in source paths. Effectviely allows
symbolic links to be copied when the link target is not valid
or there is not permission to read the link\(aqs target.
```

in man/dcp.1.

**Comment by ofaaland** [comment]
Adding backslashes or doubling the apostrophe doesn't change behavior.  `\(aq` is substituted for `'` if the source .rst file contains any of the below examples:
```
link''s
link'''s
link\'s
link\\'s
link\\\'s
```

**Comment by ofaaland** [comment]
"aq" means "apostrophe, neutral single quote" in groff:
https://man7.org/linux/man-pages/man7/groff_char.7.html

and indeed, when I look at the dcp.1 man page produced by sphinx which has `the link\(aqs target` using the command-line man page rader on rhel 8.10, the apostrophe appears as it should.

**Comment by ofaaland** [comment]
@gonsie I believe this is not really a problem, and `\(aq` is the correct substitution for ```.  Do you have any reason to think otherwise?  If not, I'll close this as notabug.

**Comment by gonsie** [comment]
If it seems to be the correct code, then go ahead and close the issue. Thanks.
Elsa Gonsiorowski

**Comment by ofaaland** [comment]
Not a bug
