### ISSUE TITLE
dfilemaker floating point exception

### ISSUE THREAD

**Issue by carbonneau1** [hpc/mpifileutils#602]
using dfilemaker to create large file with deep tree renders  Floating point exception:

following parameters were used:
dfilemaker   ntotal 1000000000    nlevels 100      maxflen21990232555520

[mutt6:321964] *** Process received signal ***
[mutt6:321964] Signal: Floating point exception (8)
[mutt6:321964] Signal code:  (-6)
[mutt6:321964] Failing at address: 0x7b1b0004e9ac
[mutt6:321964] [ 0] /lib64/libc.so.6(+0x4e5b0)[0x1555542b45b0]
[mutt6:321964] [ 1] /g/g0/carbonne/build/src/dfilemaker/dfilemaker(main+0x534)[0x403f9b]
[mutt6:321964] [ 2] /lib64/libc.so.6(__libc_start_main+0xe5)[0x1555542a07e5]
[mutt6:321964] [ 3] /g/g0/carbonne/build/src/dfilemaker/dfilemaker(_start+0x2e)[0x4024ee]
[mutt6:321964] *** End of error message ***
Floating point exception (core dumped)

This issue needs to be addressed before we put dfilemaker in production.

**Comment by ofaaland** [comment]
@carbonneau1 what args and node/process counts triggered this?

**Comment by ofaaland** [comment]
@carbonneau1 I'm unable to reproduce this with the current dfilemaker code, which has changed a lot with Levatin's commits and mine.  Please try again and let me know if you can still reproduce the issue.

**Comment by carbonneau1** [comment]
I was waiting for your changes that are in the area of the failure. I will test it again and let you know.

**Comment by carbonneau1** [comment]
After the changes from Olaf we can no longer reproduce this issue. I am closing it.
