### ISSUE TITLE
dsync options parser crash when passed bad options

### ISSUE THREAD

**Issue by carbonneau1** [hpc/mpifileutils#608]
Mixed up flags from srun into dsync and got a segmentation violation:
> build/src/dsync/dsync -o /this/is/wrong/and/shouldnot/crash
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   mutt6
  Local device: hfi1_0
--------------------------------------------------------------------------
expression /this/is/wrong/and/shouldnot/crash illegal, field "/this/is/wrong/and/shouldnot/crash", state "(null)"
failed to parse expression "/this/is/wrong/and/shouldnot/crash"
failed to parse conjunction "/this/is/wrong/and/shouldnot/crash"
[mutt6:3600031:0:3600031] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace (tid:3600031) ====
 0  /lib64/libucs.so.0(ucs_handle_error+0x2dc) [0x15553f07407c]
 1  /lib64/libucs.so.0(+0x3125c) [0x15553f07425c]
 2  /lib64/libucs.so.0(+0x3142a) [0x15553f07442a]
 3  build/src/dsync/dsync() [0x402dd4]
 4  build/src/dsync/dsync() [0x408a62]
 5  build/src/dsync/dsync() [0x408d9b]
 6  build/src/dsync/dsync() [0x409812]
 7  build/src/dsync/dsync(main+0x7e0) [0x40a120]
 8  /lib64/libc.so.6(__libc_start_main+0xe5) [0x1555539567e5]
 9  build/src/dsync/dsync(_start+0x2e) [0x402c0e]
=================================
[mutt6:3600031] *** Process received signal ***
[mutt6:3600031] Signal: Segmentation fault (11)
[mutt6:3600031] Signal code:  (-6)
[mutt6:3600031] Failing at address: 0x7b1b0036ee9f
[mutt6:3600031] [ 0] /lib64/libc.so.6(+0x4e5b0)[0x15555396a5b0]
[mutt6:3600031] [ 1] build/src/dsync/dsync[0x402dd4]
[mutt6:3600031] [ 2] build/src/dsync/dsync[0x408a62]
[mutt6:3600031] [ 3] build/src/dsync/dsync[0x408d9b]
[mutt6:3600031] [ 4] build/src/dsync/dsync[0x409812]
[mutt6:3600031] [ 5] build/src/dsync/dsync(main+0x7e0)[0x40a120]
[mutt6:3600031] [ 6] /lib64/libc.so.6(__libc_start_main+0xe5)[0x1555539567e5]
[mutt6:3600031] [ 7] build/src/dsync/dsync(_start+0x2e)[0x402c0e]
[mutt6:3600031] *** End of error message ***
Segmentation fault (core dumped)

**Comment by ofaaland** [comment]
Hi @carbonneau1 was this fixed by #612 ?

**Comment by carbonneau1** [comment]
YES

From: Olaf Faaland ***@***.***>
Date: Tuesday, December 3, 2024 at 3:10 PM
To: hpc/mpifileutils ***@***.***>
Cc: Carbonneau, Eric Joseph Jean ***@***.***>, Mention ***@***.***>
Subject: Re: [hpc/mpifileutils] dsync options parser crash when passed bad options (Issue #608)

Hi @carbonneau1<https://urldefense.us/v3/__https:/github.com/carbonneau1__;!!G2kpM7uM-TzIFchu!1iDNl1yU6anJnR47SIgVMewIGbeVzbbZ6yet5104hvx9myJE0wz9sv7YSlSDRLQJHR8jjl-PFBIfMyDHiJetZt6Aow5J$> was this fixed by #612<https://urldefense.us/v3/__https:/github.com/hpc/mpifileutils/pull/612__;!!G2kpM7uM-TzIFchu!1iDNl1yU6anJnR47SIgVMewIGbeVzbbZ6yet5104hvx9myJE0wz9sv7YSlSDRLQJHR8jjl-PFBIfMyDHiJetZmeheE60$> ?

**Comment by ofaaland** [comment]
Fixed by #612
