### ISSUE TITLE
dsync deleting destination files without the -D flag given

### ISSUE THREAD

**Issue by defaziogiancarlo** [hpc/mpifileutils#616]
During a file system migration, there are many instances where the dsync output logs show a positive number of files being deleted from the destination file system, but the -D was not given to dsync. The sbatch files are saved and do not have the -D flag.

**Comment by carbonneau1** [comment]
The current state of the source code does not allow any deletion in the destination if the walk failed. 
On the other hand if the walk of both source and destination are successful and files were deleted by a user on the source side, between 2 rounds of dsync, the files will exist only on the destination side and will be deleted. This behavior is as designed. I am closing this issue.
