### ISSUE TITLE
dsync: extract dcmp --sync functionality into separate tool

### ISSUE THREAD

**Issue by adammoody** [hpc/mpifileutils#70]
Having separate tools for each task will simplify the code for both use cases.

**Comment by KnightKu** [comment]
Hi @adammoody , is any guy working on this issue? If not, we can help on it.

**Comment by dsikich** [comment]
@KnightKu Did you plan to start on it right away? We had planned to work on it, but haven't got to it yet.

**Comment by adammoody** [comment]
dsync merged into master.  Thanks, @dsikich
