### ISSUE TITLE
dstripe: add graceful failure for --report on NFS files

### ISSUE THREAD

**Issue by adammoody** [hpc/mpifileutils#71]
Currently, we get the following error:

retrieving file stripe information for '/path/to/file',  has failed, Inappropriate ioctl for device
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
PMGR_COLLECTIVE ERROR: rank 0 on cab690: Called pmgr_abort() Code: 1, Msg: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

**Comment by dinatale2** [comment]
I suspect that the lustre API is using an ioctl to try and get stripe info without checking if the file path is part of a lustre FS. If that is the case, we can introduce a `statfs` and check for lustre's magic number(s).

**Comment by adammoody** [comment]
@dinatale2, that sounds good to me.  I suspect it may take some effort to get the statfs in there.  We can target that for a later release.

For now, would it be possible to print a warning about the file, skip it, and continue on rather than bail with an abort?  If that is also a lot of work, we can leave it how it is.

**Comment by dinatale2** [comment]
@adammoody If we print a warning to either stdout or stderr, it would mess up the table output we are generating for the user. Would simply skipping the file be sufficient?

**Comment by adammoody** [comment]
Right, good point.  Is it possible to indicate some info on the line where we'd otherwise print info for that file?

**Comment by dinatale2** [comment]
I can try and work something out to indicate it's not a file on a lustre file system.

**Comment by dinatale2** [comment]
@adammoody, actually that error is generated by dstripe if we couldn't obtain a layout from the lustre api. I might have a cleaner solution, PR should be arriving soon.
