### ISSUE TITLE
Review github pages website mailing lists

### ISSUE THREAD

**Issue by bringhurst** [hpc/mpifileutils#81]
If the Google groups mailing lists are no longer being used, the current official mailing lists should be updated on the (github pages) website.

**Comment by bringhurst** [comment]
Hey @adammoody, @gonsie ... are the mailing lists at http://hpc.github.io/mpifileutils correct?

**Comment by dinatale2** [comment]
@bringhurst I went ahead and submitted a pull request to update the mailing list (PR #83).
