### ISSUE TITLE
timestamp is not updated properly

### ISSUE THREAD

**Issue by sihara** [hpc/mpifileutils#94]
this is tested on Lustre for src and dst. "--preserved" should be enabled in dcmp, but mtime seems to be updated, but last data seems to be still in cache on client and not arrived yet. At the end, mtime seems to re-updated when last data arrived.

ls -l /scratch0/dir/a 
-rw-r--r-- 1 root root 4 Dec  4 13:35 /scratch0/dir/a
mpirun -np 16 dcmp --sync /scratch0 /scratch1
ls -l /scratch0/dir/a 
-rw-r--r-- 1 root root 4 Dec  4 13:35 /scratch0/dir/a
ls -l /scratch1/dir/a 
-rw-r--r-- 1 root root 4 Dec  4 13:51 /scratch1/dir/a

**Comment by dsikich** [comment]
@sihara  This feature in particular is not officially part of the v0.7 release. It is still quite rough. The plan is to extract the --sync option into it's own dsync tool. We will make sure this is in v0.8. Thank you for bringing this to our attention.

**Comment by sihara** [comment]
@dsikich Oh, OK. but @KnightKu found a root cause.  we will give patch shortly.

**Comment by dsikich** [comment]
@sihara Ok, if you already have a fix that is great.
